language: python
python:
  - "3.5"
before_install:
  - touch /home/fullchain.pem
  - touch /home/privkey.pem
  - mv config/travis-secrets.yaml config/secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c ./config --script check_config
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
