- id: '1537673629494'
  alias: Alarm
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      brightness_pct: '2'
      entity_id: light.ge_12724_3way_dimmer_switch_level
    service: light.turn_on
- id: '1538009987325'
  alias: Telegram Test
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      data:
        inline_keyboard:
        - Task 1:/command1, Task 2:/command2
        - Task 3:/command3, Task 4:/command4
      message: Using TheBorenBot to send a message
      title: '*Send a message*'
    service: notify.telegram_notify
- id: '1542059544164'
  alias: Basement Gas Alarm
  trigger:
  - entity_id: binary_sensor.gas_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: There is gas in the basement!!
      title: ALERT
    service: notify.telegram_notify
- id: '1542675379332'
  alias: Away Lights
  trigger:
  - event: sunset
    offset: '-25'
    platform: sun
  - at: '21:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: alarm_control_panel.simplisafe
    state: arm_away
  action:
  - data:
      entity_id: group_all lights
    service: homeassistant.toggle
- id: '1546703559532'
  alias: Normal Heat Program Day
  trigger:
  - at: 06:00:00
    platform: time
  condition:
  - condition: state
    entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
    state: heat
  action:
  - data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      temperature: '69'
    service: climate.set_temperature
- id: '1546703770731'
  alias: Normal Heat Program Night
  trigger:
  - at: '22:07:00'
    platform: time
  condition:
  - condition: state
    entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
    state: heat
  action:
  - data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      temperature: '65'
    service: climate.set_temperature
