- id: '1537673629494'
  alias: Alarm
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      brightness_pct: '2'
      entity_id: light.ge_12724_3way_dimmer_switch_level
    service: light.turn_on
- id: '1538009987325'
  alias: Telegram Test
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      data:
        inline_keyboard:
        - Task 1:/command1, Task 2:/command2
        - Task 3:/command3, Task 4:/command4
      message: Using TheBorenBot to send a message
      title: '*Send a message*'
    service: notify.telegram_notify
- id: '1542059544164'
  alias: Basement Gas Alarm
  trigger:
  - entity_id: binary_sensor.gas_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: There is gas in the basement!!
      title: 'ALERT'
    service: notify.telegram_notify
