group.all_lights:
  hidden: false
  friendly_name: Lights
group.all_automations:
  hidden: false
  friendly_name: Automation
group.all_devices:
  hidden: false
sensor.2gig_technologies_ct101_thermostat_iris_indicator:
  device_class: humidity
climate.2gig_technologies_ct101_thermostat_iris_heating_1:
  friendly_name: Heat
climate.2gig_technologies_ct101_thermostat_iris_cooling_1:
  friendly_name: A/C
switch.tv_power:
  friendly_name: TV Power
sensor.yr_symbol:
  friendly_name: Current Weather
