# Example configuration.yaml entry

outdoorLights:
  name: Outdoor Lights
  entities:
    - switch.jasco_products_14291_in_wall_smart_switch_switch_2
    - switch.jasco_products_14291_in_wall_smart_switch_switch

indoorLights:
  name: Indoor Lights
  entities:
    - light.ge_12724_3way_dimmer_switch_level
    - light.ge_12724_3way_dimmer_switch_level_2
    - switch.hall_light
    - light.ge_12724_3way_dimmer_switch_level_3
    - switch.dining_room_light
