default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.all_lights
    - group.all_automations
    - group.all_switches
    - sun.sun
    - sensor.yr_symbol
    - media_player.kitchen
    - media_player.living_room
    - media_player.65_tcl_roku_tv
    - media_player.denon_avrs640h
    - alarm_control_panel.simplisafe
    - device_tracker.chase_boren
    - switch.ge_14282_plugin_twooutlet_smart_switch_switch
    - switch.tv_power
    - binary_sensor.gas_sensor
