good_night:
   alias: 'Good Night'
   sequence:
      # This is written using the Script Syntax
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_lights
    - service: alarm_control_panel.arm_home
