#dummy secrets to support CI testing
some_password: 00000
simplisafe_pwd: 000000
simplisafe_uname: xxxx@asdf.com
telegram_api_key: 0000000
telegram_chase: 000000
http_api_password: 000000
sslCertPath: /home/fullchain.pem
sslKeyPath: /home/privkey.pem
baseUrl: 000000
darksky_api_key: 000000
lat: 00.000
long: 00.000